site_name: Statv API 参考
repo_url: https://github.com/GraiaProject/statv
repo_name: GraiaProject/statv
edit_uri: blob/master/docs
copyright: Copyright &copy; Graia Project 2021-2022.

nav:
  - Statv: index.md

theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top

  name: material
  language: zh
  icon:
    repo: fontawesome/brands/git-alt
    logo: material/file-document-multiple-outline

  font:
    text: Noto Sans Simplified Chinese
    code: JetBrains Mono

  custom_dir: docs/overrides

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: 黑暗模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: 明亮模式

extra_css:
  - "assets/chat.css"
  - "assets/extra.css"
  - "assets/curtain.css"

extra_javascript:
  - "assets/admonition.js"

extra:
  social:
    - icon: fontawesome/brands/qq
      link: https://jq.qq.com/?_wv=1027&k=VXp6plBD
      name: QQ 群
    - icon: material/compass
      link: https://graiax.cn/
      name: Graiax 社区
    - icon: fontawesome/brands/github
      link: https://github.com/GraiaProject
      name: GitHub 组织
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

watch:
  - statv.py

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition # 提示块
  - footnotes # 脚注
  - meta # 定义元数据, 通过文章上下文控制, 如disqus
  - pymdownx.caret # 下划线上标
  - pymdownx.tilde # 删除线下标
  - pymdownx.critic # 增加删除修改高亮注释, 可修饰行内或段落
  - pymdownx.details # 提示块可折叠
  - pymdownx.inlinehilite # 行内代码高亮
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.mark # 文本高亮
  - pymdownx.smartsymbols # 符号转换
  - pymdownx.superfences # 代码嵌套在列表里
  - pymdownx.keys
  - codehilite: # 代码高亮, 显示行号
      guess_lang: false
      linenums: true
  - toc: # 锚点
      permalink: 🔗
  - pymdownx.arithmatex # 数学公式
  - pymdownx.tasklist: # 复选框checklist
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/zh-cn/3/objects.inv
          selection:
            docstring_style: google
          rendering:
            show_submodules: false
            show_signature_annotations: yes
            separate_signature: yes
            docstring_section_style: list
            line_length: 80

  - section-index
