name: Test & Track
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        name: Ensure Python Runtime
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Ensure PDM & twine
        run: |
          python3 -m pip install pdm
      - name: Install Package
        run: |
          pdm install
      - name: Run Tests
        run: |
          pdm run coverage run -m pytest
          pdm run coverage xml
      - name: Report
        run: |
          pdm run coverage report
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml